use serde::{Deserialize, Serialize};
use strum::EnumIter;

#[non_exhaustive]
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq, Hash, EnumIter)]
pub enum KeyboardInput {
    Backquote,
    Backslash,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,
    AltLeft,
    AltRight,
    Backspace,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    MetaLeft,
    MetaRight,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    Convert,
    KanaMode,
    Lang1,
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    NonConvert,
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,
    NumpadSubtract,
    Escape,
    Fn,
    FnLock,
    PrintScreen,
    ScrollLock,
    Pause,
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,
    Hyper,
    Super,
    Turbo,
    Abort,
    Resume,
    Suspend,
    Again,
    Copy,
    Cut,
    Find,
    Open,
    Paste,
    Props,
    Select,
    Undo,
    Hiragana,
    Katakana,
    Unidentified,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,
}

#[cfg(desktop)]
mod desktop {
    use super::KeyboardInput;
    use crate::input::Input;
    use winit::keyboard::KeyCode;
    impl TryFrom<KeyCode> for Input {
        type Error = (); // This should be optimized out to a simple cast
        fn try_from(value: KeyCode) -> Result<Self, Self::Error> {
            Ok(match value {
                KeyCode::Backquote => Input::Keyboard(KeyboardInput::Backquote),
                KeyCode::Backslash => Input::Keyboard(KeyboardInput::Backslash),
                KeyCode::BracketLeft => Input::Keyboard(KeyboardInput::BracketLeft),
                KeyCode::BracketRight => Input::Keyboard(KeyboardInput::BracketRight),
                KeyCode::Comma => Input::Keyboard(KeyboardInput::Comma),
                KeyCode::Digit0 => Input::Keyboard(KeyboardInput::Digit0),
                KeyCode::Digit1 => Input::Keyboard(KeyboardInput::Digit1),
                KeyCode::Digit2 => Input::Keyboard(KeyboardInput::Digit2),
                KeyCode::Digit3 => Input::Keyboard(KeyboardInput::Digit3),
                KeyCode::Digit4 => Input::Keyboard(KeyboardInput::Digit4),
                KeyCode::Digit5 => Input::Keyboard(KeyboardInput::Digit5),
                KeyCode::Digit6 => Input::Keyboard(KeyboardInput::Digit6),
                KeyCode::Digit7 => Input::Keyboard(KeyboardInput::Digit7),
                KeyCode::Digit8 => Input::Keyboard(KeyboardInput::Digit8),
                KeyCode::Digit9 => Input::Keyboard(KeyboardInput::Digit9),
                KeyCode::Equal => Input::Keyboard(KeyboardInput::Equal),
                KeyCode::IntlBackslash => Input::Keyboard(KeyboardInput::IntlBackslash),
                KeyCode::IntlRo => Input::Keyboard(KeyboardInput::IntlRo),
                KeyCode::IntlYen => Input::Keyboard(KeyboardInput::IntlYen),
                KeyCode::KeyA => Input::Keyboard(KeyboardInput::KeyA),
                KeyCode::KeyB => Input::Keyboard(KeyboardInput::KeyB),
                KeyCode::KeyC => Input::Keyboard(KeyboardInput::KeyC),
                KeyCode::KeyD => Input::Keyboard(KeyboardInput::KeyD),
                KeyCode::KeyE => Input::Keyboard(KeyboardInput::KeyE),
                KeyCode::KeyF => Input::Keyboard(KeyboardInput::KeyF),
                KeyCode::KeyG => Input::Keyboard(KeyboardInput::KeyG),
                KeyCode::KeyH => Input::Keyboard(KeyboardInput::KeyH),
                KeyCode::KeyI => Input::Keyboard(KeyboardInput::KeyI),
                KeyCode::KeyJ => Input::Keyboard(KeyboardInput::KeyJ),
                KeyCode::KeyK => Input::Keyboard(KeyboardInput::KeyK),
                KeyCode::KeyL => Input::Keyboard(KeyboardInput::KeyL),
                KeyCode::KeyM => Input::Keyboard(KeyboardInput::KeyM),
                KeyCode::KeyN => Input::Keyboard(KeyboardInput::KeyN),
                KeyCode::KeyO => Input::Keyboard(KeyboardInput::KeyO),
                KeyCode::KeyP => Input::Keyboard(KeyboardInput::KeyP),
                KeyCode::KeyQ => Input::Keyboard(KeyboardInput::KeyQ),
                KeyCode::KeyR => Input::Keyboard(KeyboardInput::KeyR),
                KeyCode::KeyS => Input::Keyboard(KeyboardInput::KeyS),
                KeyCode::KeyT => Input::Keyboard(KeyboardInput::KeyT),
                KeyCode::KeyU => Input::Keyboard(KeyboardInput::KeyU),
                KeyCode::KeyV => Input::Keyboard(KeyboardInput::KeyV),
                KeyCode::KeyW => Input::Keyboard(KeyboardInput::KeyW),
                KeyCode::KeyX => Input::Keyboard(KeyboardInput::KeyX),
                KeyCode::KeyY => Input::Keyboard(KeyboardInput::KeyY),
                KeyCode::KeyZ => Input::Keyboard(KeyboardInput::KeyZ),
                KeyCode::Minus => Input::Keyboard(KeyboardInput::Minus),
                KeyCode::Period => Input::Keyboard(KeyboardInput::Period),
                KeyCode::Quote => Input::Keyboard(KeyboardInput::Quote),
                KeyCode::Semicolon => Input::Keyboard(KeyboardInput::Semicolon),
                KeyCode::Slash => Input::Keyboard(KeyboardInput::Slash),
                KeyCode::AltLeft => Input::Keyboard(KeyboardInput::AltLeft),
                KeyCode::AltRight => Input::Keyboard(KeyboardInput::AltRight),
                KeyCode::Backspace => Input::Keyboard(KeyboardInput::Backspace),
                KeyCode::CapsLock => Input::Keyboard(KeyboardInput::CapsLock),
                KeyCode::ContextMenu => Input::Keyboard(KeyboardInput::ContextMenu),
                KeyCode::ControlLeft => Input::Keyboard(KeyboardInput::ControlLeft),
                KeyCode::ControlRight => Input::Keyboard(KeyboardInput::ControlRight),
                KeyCode::Enter => Input::Keyboard(KeyboardInput::Enter),
                KeyCode::SuperLeft => Input::Keyboard(KeyboardInput::MetaLeft),
                KeyCode::SuperRight => Input::Keyboard(KeyboardInput::MetaRight),
                KeyCode::ShiftLeft => Input::Keyboard(KeyboardInput::ShiftLeft),
                KeyCode::ShiftRight => Input::Keyboard(KeyboardInput::ShiftRight),
                KeyCode::Space => Input::Keyboard(KeyboardInput::Space),
                KeyCode::Tab => Input::Keyboard(KeyboardInput::Tab),
                KeyCode::Convert => Input::Keyboard(KeyboardInput::Convert),
                KeyCode::KanaMode => Input::Keyboard(KeyboardInput::KanaMode),
                KeyCode::Lang1 => Input::Keyboard(KeyboardInput::Lang1),
                KeyCode::Lang2 => Input::Keyboard(KeyboardInput::Lang2),
                KeyCode::Lang3 => Input::Keyboard(KeyboardInput::Lang3),
                KeyCode::Lang4 => Input::Keyboard(KeyboardInput::Lang4),
                KeyCode::Lang5 => Input::Keyboard(KeyboardInput::Lang5),
                KeyCode::NonConvert => Input::Keyboard(KeyboardInput::NonConvert),
                KeyCode::Delete => Input::Keyboard(KeyboardInput::Delete),
                KeyCode::End => Input::Keyboard(KeyboardInput::End),
                KeyCode::Help => Input::Keyboard(KeyboardInput::Help),
                KeyCode::Home => Input::Keyboard(KeyboardInput::Home),
                KeyCode::Insert => Input::Keyboard(KeyboardInput::Insert),
                KeyCode::PageDown => Input::Keyboard(KeyboardInput::PageDown),
                KeyCode::PageUp => Input::Keyboard(KeyboardInput::PageUp),
                KeyCode::ArrowDown => Input::Keyboard(KeyboardInput::ArrowDown),
                KeyCode::ArrowLeft => Input::Keyboard(KeyboardInput::ArrowLeft),
                KeyCode::ArrowRight => Input::Keyboard(KeyboardInput::ArrowRight),
                KeyCode::ArrowUp => Input::Keyboard(KeyboardInput::ArrowUp),
                KeyCode::NumLock => Input::Keyboard(KeyboardInput::NumLock),
                KeyCode::Numpad0 => Input::Keyboard(KeyboardInput::Numpad0),
                KeyCode::Numpad1 => Input::Keyboard(KeyboardInput::Numpad1),
                KeyCode::Numpad2 => Input::Keyboard(KeyboardInput::Numpad2),
                KeyCode::Numpad3 => Input::Keyboard(KeyboardInput::Numpad3),
                KeyCode::Numpad4 => Input::Keyboard(KeyboardInput::Numpad4),
                KeyCode::Numpad5 => Input::Keyboard(KeyboardInput::Numpad5),
                KeyCode::Numpad6 => Input::Keyboard(KeyboardInput::Numpad6),
                KeyCode::Numpad7 => Input::Keyboard(KeyboardInput::Numpad7),
                KeyCode::Numpad8 => Input::Keyboard(KeyboardInput::Numpad8),
                KeyCode::Numpad9 => Input::Keyboard(KeyboardInput::Numpad9),
                KeyCode::NumpadAdd => Input::Keyboard(KeyboardInput::NumpadAdd),
                KeyCode::NumpadBackspace => Input::Keyboard(KeyboardInput::NumpadBackspace),
                KeyCode::NumpadClear => Input::Keyboard(KeyboardInput::NumpadClear),
                KeyCode::NumpadClearEntry => Input::Keyboard(KeyboardInput::NumpadClearEntry),
                KeyCode::NumpadComma => Input::Keyboard(KeyboardInput::NumpadComma),
                KeyCode::NumpadDecimal => Input::Keyboard(KeyboardInput::NumpadDecimal),
                KeyCode::NumpadDivide => Input::Keyboard(KeyboardInput::NumpadDivide),
                KeyCode::NumpadEnter => Input::Keyboard(KeyboardInput::NumpadEnter),
                KeyCode::NumpadEqual => Input::Keyboard(KeyboardInput::NumpadEqual),
                KeyCode::NumpadHash => Input::Keyboard(KeyboardInput::NumpadHash),
                KeyCode::NumpadMemoryAdd => Input::Keyboard(KeyboardInput::NumpadMemoryAdd),
                KeyCode::NumpadMemoryClear => Input::Keyboard(KeyboardInput::NumpadMemoryClear),
                KeyCode::NumpadMemoryRecall => Input::Keyboard(KeyboardInput::NumpadMemoryRecall),
                KeyCode::NumpadMemoryStore => Input::Keyboard(KeyboardInput::NumpadMemoryStore),
                KeyCode::NumpadMemorySubtract => {
                    Input::Keyboard(KeyboardInput::NumpadMemorySubtract)
                }
                KeyCode::NumpadMultiply => Input::Keyboard(KeyboardInput::NumpadMultiply),
                KeyCode::NumpadParenLeft => Input::Keyboard(KeyboardInput::NumpadParenLeft),
                KeyCode::NumpadParenRight => Input::Keyboard(KeyboardInput::NumpadParenRight),
                KeyCode::NumpadStar => Input::Keyboard(KeyboardInput::NumpadStar),
                KeyCode::NumpadSubtract => Input::Keyboard(KeyboardInput::NumpadSubtract),
                KeyCode::Escape => Input::Keyboard(KeyboardInput::Escape),
                KeyCode::Fn => Input::Keyboard(KeyboardInput::Fn),
                KeyCode::FnLock => Input::Keyboard(KeyboardInput::FnLock),
                KeyCode::PrintScreen => Input::Keyboard(KeyboardInput::PrintScreen),
                KeyCode::ScrollLock => Input::Keyboard(KeyboardInput::ScrollLock),
                KeyCode::Pause => Input::Keyboard(KeyboardInput::Pause),
                KeyCode::BrowserBack => Input::Keyboard(KeyboardInput::BrowserBack),
                KeyCode::BrowserFavorites => Input::Keyboard(KeyboardInput::BrowserFavorites),
                KeyCode::BrowserForward => Input::Keyboard(KeyboardInput::BrowserForward),
                KeyCode::BrowserHome => Input::Keyboard(KeyboardInput::BrowserHome),
                KeyCode::BrowserRefresh => Input::Keyboard(KeyboardInput::BrowserRefresh),
                KeyCode::BrowserSearch => Input::Keyboard(KeyboardInput::BrowserSearch),
                KeyCode::BrowserStop => Input::Keyboard(KeyboardInput::BrowserStop),
                KeyCode::Eject => Input::Keyboard(KeyboardInput::Eject),
                KeyCode::LaunchApp1 => Input::Keyboard(KeyboardInput::LaunchApp1),
                KeyCode::LaunchApp2 => Input::Keyboard(KeyboardInput::LaunchApp2),
                KeyCode::LaunchMail => Input::Keyboard(KeyboardInput::LaunchMail),
                KeyCode::MediaPlayPause => Input::Keyboard(KeyboardInput::MediaPlayPause),
                KeyCode::MediaSelect => Input::Keyboard(KeyboardInput::MediaSelect),
                KeyCode::MediaStop => Input::Keyboard(KeyboardInput::MediaStop),
                KeyCode::MediaTrackNext => Input::Keyboard(KeyboardInput::MediaTrackNext),
                KeyCode::MediaTrackPrevious => Input::Keyboard(KeyboardInput::MediaTrackPrevious),
                KeyCode::Power => Input::Keyboard(KeyboardInput::Power),
                KeyCode::Sleep => Input::Keyboard(KeyboardInput::Sleep),
                KeyCode::AudioVolumeDown => Input::Keyboard(KeyboardInput::AudioVolumeDown),
                KeyCode::AudioVolumeMute => Input::Keyboard(KeyboardInput::AudioVolumeMute),
                KeyCode::AudioVolumeUp => Input::Keyboard(KeyboardInput::AudioVolumeUp),
                KeyCode::WakeUp => Input::Keyboard(KeyboardInput::WakeUp),
                KeyCode::Meta => Input::Keyboard(KeyboardInput::Super),
                KeyCode::Hyper => Input::Keyboard(KeyboardInput::Hyper),
                KeyCode::Turbo => Input::Keyboard(KeyboardInput::Turbo),
                KeyCode::Abort => Input::Keyboard(KeyboardInput::Abort),
                KeyCode::Resume => Input::Keyboard(KeyboardInput::Resume),
                KeyCode::Suspend => Input::Keyboard(KeyboardInput::Suspend),
                KeyCode::Again => Input::Keyboard(KeyboardInput::Again),
                KeyCode::Copy => Input::Keyboard(KeyboardInput::Copy),
                KeyCode::Cut => Input::Keyboard(KeyboardInput::Cut),
                KeyCode::Find => Input::Keyboard(KeyboardInput::Find),
                KeyCode::Open => Input::Keyboard(KeyboardInput::Open),
                KeyCode::Paste => Input::Keyboard(KeyboardInput::Paste),
                KeyCode::Props => Input::Keyboard(KeyboardInput::Props),
                KeyCode::Select => Input::Keyboard(KeyboardInput::Select),
                KeyCode::Undo => Input::Keyboard(KeyboardInput::Undo),
                KeyCode::Hiragana => Input::Keyboard(KeyboardInput::Hiragana),
                KeyCode::Katakana => Input::Keyboard(KeyboardInput::Katakana),
                KeyCode::F1 => Input::Keyboard(KeyboardInput::F1),
                KeyCode::F2 => Input::Keyboard(KeyboardInput::F2),
                KeyCode::F3 => Input::Keyboard(KeyboardInput::F3),
                KeyCode::F4 => Input::Keyboard(KeyboardInput::F4),
                KeyCode::F5 => Input::Keyboard(KeyboardInput::F5),
                KeyCode::F6 => Input::Keyboard(KeyboardInput::F6),
                KeyCode::F7 => Input::Keyboard(KeyboardInput::F7),
                KeyCode::F8 => Input::Keyboard(KeyboardInput::F8),
                KeyCode::F9 => Input::Keyboard(KeyboardInput::F9),
                KeyCode::F10 => Input::Keyboard(KeyboardInput::F10),
                KeyCode::F11 => Input::Keyboard(KeyboardInput::F11),
                KeyCode::F12 => Input::Keyboard(KeyboardInput::F12),
                KeyCode::F13 => Input::Keyboard(KeyboardInput::F13),
                KeyCode::F14 => Input::Keyboard(KeyboardInput::F14),
                KeyCode::F15 => Input::Keyboard(KeyboardInput::F15),
                KeyCode::F16 => Input::Keyboard(KeyboardInput::F16),
                KeyCode::F17 => Input::Keyboard(KeyboardInput::F17),
                KeyCode::F18 => Input::Keyboard(KeyboardInput::F18),
                KeyCode::F19 => Input::Keyboard(KeyboardInput::F19),
                KeyCode::F20 => Input::Keyboard(KeyboardInput::F20),
                KeyCode::F21 => Input::Keyboard(KeyboardInput::F21),
                KeyCode::F22 => Input::Keyboard(KeyboardInput::F22),
                KeyCode::F23 => Input::Keyboard(KeyboardInput::F23),
                KeyCode::F24 => Input::Keyboard(KeyboardInput::F24),
                KeyCode::F25 => Input::Keyboard(KeyboardInput::F25),
                KeyCode::F26 => Input::Keyboard(KeyboardInput::F26),
                KeyCode::F27 => Input::Keyboard(KeyboardInput::F27),
                KeyCode::F28 => Input::Keyboard(KeyboardInput::F28),
                KeyCode::F29 => Input::Keyboard(KeyboardInput::F29),
                KeyCode::F30 => Input::Keyboard(KeyboardInput::F30),
                KeyCode::F31 => Input::Keyboard(KeyboardInput::F31),
                KeyCode::F32 => Input::Keyboard(KeyboardInput::F32),
                KeyCode::F33 => Input::Keyboard(KeyboardInput::F33),
                KeyCode::F34 => Input::Keyboard(KeyboardInput::F34),
                KeyCode::F35 => Input::Keyboard(KeyboardInput::F35),
                _ => return Err(()),
            })
        }
    }
}
